package com.jiao.testproject.testproject.entity;

import java.io.Serializable;

public class shareFileEntity extends shareFileEntityKey implements Serializable {
    /** 
    * 
    * DB Column Name: is_share
    */
    private Integer isShare;

    /** 
    * 
    * DB Column Name: file_size
    */
    private String fileSize;

    /** 
    * 
    * DB Column Name: file_create_time
    */
    private String fileCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sharefile_table
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharefile_table.is_share
     *
     * @return the value of sharefile_table.is_share
     *
     * @mbggenerated
     */
    public Integer getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharefile_table.is_share
     *
     * @param isShare the value for sharefile_table.is_share
     *
     * @mbggenerated
     */
    public void setIsShare(Integer isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharefile_table.file_size
     *
     * @return the value of sharefile_table.file_size
     *
     * @mbggenerated
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharefile_table.file_size
     *
     * @param fileSize the value for sharefile_table.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize == null ? null : fileSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharefile_table.file_create_time
     *
     * @return the value of sharefile_table.file_create_time
     *
     * @mbggenerated
     */
    public String getFileCreateTime() {
        return fileCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharefile_table.file_create_time
     *
     * @param fileCreateTime the value for sharefile_table.file_create_time
     *
     * @mbggenerated
     */
    public void setFileCreateTime(String fileCreateTime) {
        this.fileCreateTime = fileCreateTime == null ? null : fileCreateTime.trim();
    }
}