package com.jiao.testproject.testproject.entity;

import java.io.Serializable;

public class shareFileEntityKey implements Serializable {
    /** 
    * 
    * DB Column Name: file_id
    */
    private Integer fileId;

    /** 
    * 
    * DB Column Name: file_name
    */
    private String fileName;

    /** 
    * 
    * DB Column Name: file_creater
    */
    private String fileCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sharefile_table
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharefile_table.file_id
     *
     * @return the value of sharefile_table.file_id
     *
     * @mbggenerated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharefile_table.file_id
     *
     * @param fileId the value for sharefile_table.file_id
     *
     * @mbggenerated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharefile_table.file_name
     *
     * @return the value of sharefile_table.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharefile_table.file_name
     *
     * @param fileName the value for sharefile_table.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharefile_table.file_creater
     *
     * @return the value of sharefile_table.file_creater
     *
     * @mbggenerated
     */
    public String getFileCreater() {
        return fileCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharefile_table.file_creater
     *
     * @param fileCreater the value for sharefile_table.file_creater
     *
     * @mbggenerated
     */
    public void setFileCreater(String fileCreater) {
        this.fileCreater = fileCreater == null ? null : fileCreater.trim();
    }
}